name: Mirror to jsc

on:
  push:
    branches: [ main ]

jobs:
  sync_to_jsc:
    runs-on: ubuntu-latest
    steps:
      - name: sycnmaster
        uses: wei/git-sync@v3
        with:
          source_repo: "gmtiddia/pippo"
          source_branch: "main"
          destination_repo: "https://ghpusher:${{ secrets.JSC_GITLAB_ACCESS_TOKEN }}@gitlab.jsc.fz-juelich.de/nest/nest-simulator.git"
          destination_branch: "jacamar-test"
          
